// NSE F&O + Nifty 100 symbols — used for after-hours historical screening
const FO_SYMBOLS = [
  'RELIANCE','TCS','INFY','HDFCBANK','ICICIBANK','WIPRO','BAJFINANCE','SBIN','AXISBANK',
  'KOTAKBANK','LT','MARUTI','TITAN','NESTLEIND','ASIANPAINT','ULTRACEMCO','SUNPHARMA',
  'TATAMOTORS','TATASTEEL','HINDALCO','JSWSTEEL','ONGC','NTPC','POWERGRID','COALINDIA',
  'ADANIENT','ADANIPORTS','BAJAJFINSV','BAJAJ-AUTO','HEROMOTOCO','EICHERMOT','M&M',
  'DIVISLAB','DRREDDY','CIPLA','APOLLOHOSP','HCLTECH','TECHM','MPHASIS','LTIM',
  'INDUSINDBK','FEDERALBNK','BANDHANBNK','IDFCFIRSTB','PNB','BANKBARODA','CANBK',
  'GRASIM','SHREECEM','AMBUJACEM','ACC','PIDILITIND','BERGEPAINT','HAVELLS','VOLTAS',
  'WHIRLPOOL','BATAINDIA','PAGEIND','TRENT','DMART','NYKAA','ZOMATO','PAYTM',
  'NAUKRI','IRCTC','INDIGO','SPICEJET','GMRINFRA','ADANIGREEN','TATAPOWER',
  'TORNTPHARM','AUROPHARMA','LUPIN','BIOCON','ALKEM','IPCALAB','ABBOTINDIA',
  'SIEMENS','ABB','BHEL','BEL','HAL','COCHINSHIP','MAZAGON','GRSE',
  'CHOLAFIN','MUTHOOTFIN','MANAPPURAM','LICHSGFIN','RECLTD','PFC','IRFC',
  'HINDUNILVR','DABUR','MARICO','COLPAL','EMAMILTD','GODREJCP','BRITANNIA',
  'ITC','UNITDSPR','RADICO','MCDOWELL-N','UBL',
  'VEDL','NMDC','SAIL','NATIONALUM','HINDCOPPER',
  'OBEROIRLTY','DLF','GODREJPROP','PRESTIGE','BRIGADE',
  'ZEEL','SUNTV','PVRINOX','INOXWIND','CESC',
];

module.exports = { FO_SYMBOLS };
